# Basic task example
- name: launch ansible cloudformation example
  cloudformation:
    stack_name: "ansible-cloudformation"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: "files/asgdemo.template"
    template_parameters: {}
    tags:
      Stack: "ansible-cloudformation"