# Basic task example
- name: launch ansible cloudformation example
  cloudformation:
    stack_name: "ansible-cloudformation"
    state: "present"
    region: "{{ region }}"
    disable_rollback: true
    template: "roles/infra2/files/asgdemo.json"
    template_parameters:
      KeyName: "{{ key_name }}"
      InstanceType: "{{ instance_size }}"
      Subnets: "{{ subnets | join(', ') }}"
      MinSize: "{{ min_size }}"
      MaxSize: "{{ max_size }}"
      DesiredSize: "{{ desired_capacity }}"
      AmiID: "{{ ami }}"
      UserData: "{{ user_data }}"
    tags:
      Stack: "ansible-cloudformation"